### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by AnhLD2610** [zfj1998/SO_Title_Generation#3]
i read your paper and i saw 4 dataset of 4 languages java, python, js and php but in your kaggle link just only java and python dataset where can i find js and php dataset?

**Comment by zfj1998** [comment]
Thank you for bringing this to my attention. You're right that my paper discussed experiments on four programming languages (Java, Python, JavaScript, PHP), but the Kaggle link only includes datasets for Java and Python.

I sincerely apologize that the JavaScript and PHP datasets are missing. The experiments for this work were conducted over two years ago while I was a graduate student. Since graduating, I no longer have access to the university lab environment where the original data was stored. Unfortunately, without access to that lab, I do not have the JSON and PHP datasets available to share anymore.

While I cannot provide those specific missing datasets, I have made the code and scripts for data preparation open source. My hope is that making this process transparent will allow others to reproduce the data collection for JavaScript and PHP if they wish to replicate or build upon the experiments. Thank you for pointing out this inconsistency. Please let me know if there are any other ways I can help address this issue.
